### ISSUE TITLE
where was your train data

### ISSUE THREAD

**Issue by w3d0z** [aliraza-aa/Cedar-Face-Recognition#1]
hello there
why dont you upload this data C:\Users\pc\Desktop\cedar-face-recog\TrainData
at your source collect_data.py line 36

its better if you give us sample data to collect...

**Comment by aliraza-aa** [comment]
Hi, I can't add the sample data because it contains personal images.

**Comment by w3d0z** [comment]
then you can give us sample data tree with other image, which in valid folder name sample and valid file name sample

so, this code can be worked well in the future
